// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReforaTec.Api.Database;

#nullable disable

namespace ReforaTec.Api.src.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731195519_AddRefreshTokensTable")]
    partial class AddRefreshTokensTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReforaTec.Api.Entities.AuthOtpCode", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("verification_code");

                    b.HasKey("UserId")
                        .HasName("pk_auth_otp_codes");

                    b.ToTable("auth_otp_codes", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("campaign_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InscriptionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("inscription_code");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedCampaignName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_campaign_name");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("InscriptionCode")
                        .IsUnique()
                        .HasDatabaseName("ix_campaigns_inscription_code");

                    b.HasIndex("TenantId", "NormalizedCampaignName")
                        .IsUnique()
                        .HasDatabaseName("ix_campaigns_tenant_id_normalized_campaign_name");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.CampaignManagesTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignFolio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("campaign_folio");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedCampaignFolio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("normalized_campaign_folio");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer")
                        .HasColumnName("tree_id");

                    b.HasKey("Id")
                        .HasName("pk_campaign_manages_trees");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_manages_trees_campaign_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_campaign_manages_trees_tenant_id");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_campaign_manages_trees_tree_id");

                    b.HasIndex("CampaignId", "NormalizedCampaignFolio")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_manages_trees_campaign_id_normalized_campaign_folio");

                    b.ToTable("campaign_manages_trees", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DetectedHealthState")
                        .HasColumnType("integer")
                        .HasColumnName("detected_health_state");

                    b.Property<DateTime>("DeviceCapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_captured_at");

                    b.Property<decimal?>("DiameterCentimeters")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("diameter_centimeters");

                    b.Property<string>("EvidencePhotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("evidence_photo_url");

                    b.Property<decimal?>("HeightCentimeters")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("height_centimeters");

                    b.Property<int>("InspectionType")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_type");

                    b.Property<int>("InspectorId")
                        .HasColumnType("integer")
                        .HasColumnName("inspector_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ObservationNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observation_notes");

                    b.Property<DateTime?>("ServerSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_synced_at");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer")
                        .HasColumnName("tree_id");

                    b.HasKey("Id")
                        .HasName("pk_measurements");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_measurements_campaign_id");

                    b.HasIndex("InspectorId")
                        .HasDatabaseName("ix_measurements_inspector_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_measurements_tenant_id");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_measurements_tree_id");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_body");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int?>("TargetHealthState")
                        .HasColumnType("integer")
                        .HasColumnName("target_health_state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notification_templates");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_notification_templates_type");

                    b.ToTable("notification_templates", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audience");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hashed_token")
                        .IsFixedLength();

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_refresh_tokens_expires_at");

                    b.HasIndex("HashedToken")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_refresh_tokens_hashed_token");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_auth_refresh_tokens_user_id_created_at");

                    b.ToTable("auth_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeviceCapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_captured_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<DateTime?>("ServerSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("server_synced_at");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer")
                        .HasColumnName("tree_id");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_services_campaign_id");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_services_service_type_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_services_student_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_services_tenant_id");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_services_tree_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_service_name");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_name");

                    b.HasKey("Id")
                        .HasName("pk_service_types");

                    b.HasIndex("NormalizedServiceName")
                        .IsUnique()
                        .HasDatabaseName("ix_service_types_normalized_service_name");

                    b.ToTable("service_types", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("common_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedCommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_common_name");

                    b.Property<string>("NormalizedScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_scientific_name");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("NormalizedCommonName")
                        .HasDatabaseName("ix_species_normalized_common_name");

                    b.HasIndex("NormalizedScientificName")
                        .IsUnique()
                        .HasDatabaseName("ix_species_normalized_scientific_name");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acronym");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("institution_name");

                    b.Property<string>("InstitutionalEmailDomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("institutional_email_domain");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedInstitutionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_institution_name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("InstitutionalEmailDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_institutional_email_domain");

                    b.HasIndex("NormalizedInstitutionName")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_normalized_institution_name");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DiameterCentimeters")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("diameter_centimeters");

                    b.Property<int>("HealthState")
                        .HasColumnType("integer")
                        .HasColumnName("health_state");

                    b.Property<decimal?>("HeightCentimeters")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("height_centimeters");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PlantingDate")
                        .HasColumnType("date")
                        .HasColumnName("planting_date");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer")
                        .HasColumnName("species_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ValueId")
                        .HasColumnType("integer")
                        .HasColumnName("value_id");

                    b.HasKey("Id")
                        .HasName("pk_trees");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_trees_species_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_trees_tenant_id");

                    b.HasIndex("ValueId")
                        .HasDatabaseName("ix_trees_value_id");

                    b.ToTable("trees", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("control_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRole")
                        .HasColumnType("integer")
                        .HasColumnName("current_role");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("second_last_name");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId", "ControlNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_control_number");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.UserCaresForTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer")
                        .HasColumnName("tree_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_cares_for_trees");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_user_cares_for_trees_campaign_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_cares_for_trees_tenant_id");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_user_cares_for_trees_tree_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_cares_for_trees_user_id");

                    b.ToTable("user_cares_for_trees", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_token");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("OsType")
                        .HasColumnType("integer")
                        .HasColumnName("os_type");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("DeviceToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_devices_device_token");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_devices_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_devices_user_id");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.UserInspectsCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_inspects_campaigns");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_user_inspects_campaigns_campaign_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_inspects_campaigns_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_inspects_campaigns_user_id");

                    b.ToTable("user_inspects_campaigns", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedValueName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("normalized_value_name");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("value_name");

                    b.HasKey("Id")
                        .HasName("pk_values");

                    b.HasIndex("NormalizedValueName")
                        .IsUnique()
                        .HasDatabaseName("ix_values_normalized_value_name");

                    b.ToTable("values", (string)null);
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.AuthOtpCode", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("ReforaTec.Api.Entities.AuthOtpCode", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_otp_codes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Campaign", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_tenants_tenant_id");

                    b.OwnsOne("ReforaTec.Api.Entities.Common.Location", "Location", b1 =>
                        {
                            b1.Property<int>("CampaignId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_neighborhood");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_street");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_street_number");

                            b1.HasKey("CampaignId");

                            b1.ToTable("campaigns");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId")
                                .HasConstraintName("fk_campaigns_campaigns_id");
                        });

                    b.OwnsOne("ReforaTec.Api.Entities.Common.Period", "Period", b1 =>
                        {
                            b1.Property<int>("CampaignId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("period_end_date");

                            b1.Property<DateOnly?>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("period_start_date");

                            b1.HasKey("CampaignId");

                            b1.ToTable("campaigns");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId")
                                .HasConstraintName("fk_campaigns_campaigns_id");
                        });

                    b.Navigation("Location");

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.CampaignManagesTree", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_manages_trees_campaigns_campaign_id");

                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_manages_trees_tenants_tenant_id");

                    b.HasOne("ReforaTec.Api.Entities.Tree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_manages_trees_trees_tree_id");

                    b.Navigation("Campaign");

                    b.Navigation("Tenant");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Measurement", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_measurements_campaigns_campaign_id");

                    b.HasOne("ReforaTec.Api.Entities.User", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurements_users_inspector_id");

                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurements_tenants_tenant_id");

                    b.HasOne("ReforaTec.Api.Entities.Tree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurements_trees_tree_id");

                    b.Navigation("Campaign");

                    b.Navigation("Inspector");

                    b.Navigation("Tenant");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Service", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_services_campaigns_campaign_id");

                    b.HasOne("ReforaTec.Api.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_services_service_types_service_type_id");

                    b.HasOne("ReforaTec.Api.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_services_users_student_id");

                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_services_tenants_tenant_id");

                    b.HasOne("ReforaTec.Api.Entities.Tree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_services_trees_tree_id");

                    b.Navigation("Campaign");

                    b.Navigation("ServiceType");

                    b.Navigation("Student");

                    b.Navigation("Tenant");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.Tree", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trees_species_species_id");

                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trees_tenants_tenant_id");

                    b.HasOne("ReforaTec.Api.Entities.Value", "Value")
                        .WithMany()
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trees_values_value_id");

                    b.OwnsOne("ReforaTec.Api.Entities.Common.Location", "Location", b1 =>
                        {
                            b1.Property<int>("TreeId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_neighborhood");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_street");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_street_number");

                            b1.HasKey("TreeId");

                            b1.ToTable("trees");

                            b1.WithOwner()
                                .HasForeignKey("TreeId")
                                .HasConstraintName("fk_trees_trees_id");
                        });

                    b.Navigation("Location");

                    b.Navigation("Species");

                    b.Navigation("Tenant");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.User", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.UserCaresForTree", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_cares_for_trees_campaigns_campaign_id");

                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_cares_for_trees_tenants_tenant_id");

                    b.HasOne("ReforaTec.Api.Entities.Tree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_cares_for_trees_trees_tree_id");

                    b.HasOne("ReforaTec.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_cares_for_trees_users_user_id");

                    b.Navigation("Campaign");

                    b.Navigation("Tenant");

                    b.Navigation("Tree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.UserDevice", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_tenants_tenant_id");

                    b.HasOne("ReforaTec.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReforaTec.Api.Entities.UserInspectsCampaign", b =>
                {
                    b.HasOne("ReforaTec.Api.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_inspects_campaigns_campaigns_campaign_id");

                    b.HasOne("ReforaTec.Api.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_inspects_campaigns_tenants_tenant_id");

                    b.HasOne("ReforaTec.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_inspects_campaigns_users_user_id");

                    b.Navigation("Campaign");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
