@host = localhost:5210

###
POST {{host}}/api/v1/trees
Content-Type: application/json

{
  "plantingDate": "2024-03-15",
  "valueId": 0,
  "speciesId": -5,
  "height": -10.0,
  "location": {
    "latitude": 22.2167,
    "longitude": -97.8500,
    "street": "",
    "neighborhood": "   ",
    "streetNumber": ""
  }
}

###
GET {{host}}/api/v1/trees
Content-Type: application/json

###
GET {{host}}/api/v1/trees/2
Content-Type: application/json


###
GET {{host}}/api/v1/trees/0
Content-Type: application/json


### 
POST {{host}}/api/v1/values
Content-Type: application/json

{
  "valueName": "Esperanza"
}

### 
POST {{host}}/api/v1/values
Content-Type: application/json

{
  "valueName": "   "
}

### 
POST {{host}}/api/v1/values
Content-Type: application/json

{
  "valueName": "Madera123!"
}

###
GET {{host}}/api/v1/values/1
Content-Type: application/json